In [1]:
import pandas as pd

import threading,time

In [2]:
def SuperTrend(data , period = 10, multiplier=3, ohlc=['open', 'high', 'low', 'close']):
        global supertrend
        data['tr0'] = abs(data["high"] - data["low"])
        data['tr1'] = abs(data["high"] - data["close"].shift(1))
        data['tr2'] = abs(data["low"]- data["close"].shift(1))
        data["TR"] = round(data[['tr0', 'tr1', 'tr2']].max(axis=1),2)
#         tr=round([abs(data["high"] - data["low"]),abs(data["high"] - data["close"].shift(1)),abs(data["low"]- data["close"].shift(1))].max(axis=1),2)
        data["ATR"]=0.00
        data['BUB']=0.00
        data["BLB"]=0.00
        data["final_ub"]=0.00
        data["final_lb"]=0.00
        data["ST"]=0.00
        for i, row in data.iterrows():
            if i == 0:
                data.loc[i,'ATR'] = 0.00#data['ATR'].iat[0]
            else:
                data.loc[i,'ATR'] = ((data.loc[i-1,'ATR'] * (period-1))+data.loc[i,'TR'])/period
        data['BUB'] = round(((data["high"] + data["low"]) / 2) + (multiplier * data["ATR"]),2)
        data['BLB'] = round(((data["high"] + data["low"]) / 2) - (multiplier * data["ATR"]),2)
        for i, row in data.iterrows():
            if i==0:
                data.loc[i,"final_ub"]=0.00
            else:
                if (data.loc[i,"BUB"]<data.loc[i-1,"final_ub"])|(data.loc[i-1,"close"]>data.loc[i-1,"final_ub"]):
                    data.loc[i,"final_ub"]=data.loc[i,"BUB"]
                else:
                    data.loc[i,"final_ub"]=data.loc[i-1,"final_ub"]

        for i, row in data.iterrows():
            if i==0:
                data.loc[i,"final_lb"]=0.00
            else:
                if (data.loc[i,"BLB"]>data.loc[i-1,"final_lb"])|(data.loc[i-1,"close"]<data.loc[i-1,"final_lb"]):
                    data.loc[i,"final_lb"]=data.loc[i,"BLB"]
                else:
                    data.loc[i,"final_lb"]=data.loc[i-1,"final_lb"]

        for i, row in data.iterrows():
            if i==0:
                data.loc[i,"ST"]=0.00
            elif (data.loc[i-1,"ST"]==data.loc[i-1,"final_ub"]) & (data.loc[i,"close"]<=data.loc[i,"final_ub"]):
                data.loc[i,"ST"]=data.loc[i,"final_ub"]
            elif (data.loc[i-1,"ST"]==data.loc[i-1,"final_ub"])&(data.loc[i,"close"]>data.loc[i,"final_ub"]):
                data.loc[i,"ST"]=data.loc[i,"final_lb"]
            elif (data.loc[i-1,"ST"]==data.loc[i-1,"final_lb"])&(data.loc[i,"close"]>=data.loc[i,"final_lb"]):
                data.loc[i,"ST"]=data.loc[i,"final_lb"]
            elif (data.loc[i-1,"ST"]==data.loc[i-1,"final_lb"])&(data.loc[i,"close"]<data.loc[i,"final_lb"]):
                data.loc[i,"ST"]=data.loc[i,"final_ub"]

        # Buy Sell Indicator
        for i, row in data.iterrows():
            if i==0:
                data["STX"]="NA"
            elif (data.loc[i,"ST"]<data.loc[i,"close"]) :
                data.loc[i,"STX"]="green"
            else:
                data.loc[i,"STX"]="red"
        data.drop(['tr0', 'tr1', 'tr2', 'TR','BUB', 'BLB'], inplace=True, axis=1)
        return data

In [4]:
def getData(token, fromm, to, time_frame):
    global last_row,df
    data=re.get(f"https://api.kite.trade/instruments/historical/{token}/{time_frame}?from={fromm}&to={to}",headers=headers)
#     print("data-->", data.json())
    df=pd.DataFrame(data.json()['data']['candles'])
    df.columns = ["Timestamp", "open", "high", "low","close","volume"]
#     print(SuperTrend(df))
    last_row = SuperTrend(df).iloc[-1]

In [5]:
def getDataThread():
    global last_row, last_time,df
    while True:
        time.sleep(1)
        if str(parser.parse(last_time.replace("T"," "))+datetime.timedelta(minutes=interval*2))<str(datetime.datetime.now()):
            from_date = datetime.datetime.now()-datetime.timedelta(days=30)
            to_date = datetime.datetime.now()-datetime.timedelta(minutes=interval)
            getData(5097729,from_date, to_date, time_frame )
            last_time=last_row.Timestamp
            print('running',datetime.datetime.now(),last_time,last_row.Timestamp,last_row.open,last_row.high,last_row.low,last_row.close,last_row.volume,last_row.ST,last_row.STX,'side=sell'if last_row.STX=='red' else 'side=buy','qty=2','change=True' if last_row.STX!=last_signal else 'change=False')

In [6]:
from dateutil import parser
import requests as re
API_KEY="rfnqn5jyts2ljcq1"
# RUBbPfsVE3sbiBpIk109eAY4L8cOvdnv
# VkjKYp51T2TgvvHNPukdY5K2gRttR3W7
ACCESS_TOKEN="wjuPdCyYoYyFfZJ0j92I4m3ggw2FVpir"
headers={"X-Kite-Version":'3','Authorization':"token "+API_KEY+":"+ACCESS_TOKEN}
ROOT_ENDPOINT="https://api.kite.trade"
API_SECRET="4t8tlmijcewpoov8nayd978x7bpj4yif"



interval=3
import datetime,time

from_date = datetime.datetime.now()-datetime.timedelta(days=30)
to_date = datetime.datetime.now()-datetime.timedelta(minutes=interval)
if interval==1:
    time_frame = 'minute'
    
else:
    time_frame = str(interval)+'minute'
    
getData(5097729,from_date, to_date, time_frame )

last_time=last_row.Timestamp
last_signal=last_row.STX
print('running',datetime.datetime.now(),last_time,last_row.Timestamp,last_row.open,last_row.high,last_row.low,last_row.close,last_row.volume,last_row.ST,last_row.STX,'side=sell'if last_row.STX=='red' else 'side=buy','qty=1','change=True')
#         adding data in file here
f = open("marketData.txt", "a")
d = f"{datetime.datetime.now()},{last_time,last_row.Timestamp},{last_row.open},{last_row.high},{last_row.low},{last_row.close},{last_row.volume},{last_row.ST},{last_row.STX},{'side=sell'if last_row.STX=='red' else 'side=buy'},{'qty=2'},{'change=True' if last_row.STX!=last_signal else 'change=False'}"
f.write(d)
# f.write(f"{datetime.datetime.now()},{last_time,last_row.Timestamp},{last_row.open},{last_row.high},{last_row.low},{last_row.close},{last_row.volume},{last_row.ST},{last_row.STX},{'side=sell'if last_row.STX=='red' else 'side=buy'},{'qty=2'},{'change=True' if last_row.STX!=last_signal else 'change=False'}")
# order_plc =  place_order(ROOT_ENDPOINT,headers,"NSE","ICICIBANK",1000,'SELL'if last_row.STX=='red' else 'BUY')
# print(order_plc)

# running 2023-03-24 13:58:41.163117 2023-03-24T13:54:00+0530 3357.65 3359.65 3355.3 3357.8 424 3367.48 red side=sell qty 1or2 change=True
t1 = threading.Thread(target=getDataThread)
t1.start()
# while True:
#     time.sleep(1)
#     if str(parser.parse(last_time.replace("T"," "))+datetime.timedelta(minutes=interval*2))<str(datetime.datetime.now()):
        
       
#         print('running',datetime.datetime.now(),last_time,last_row.Timestamp,last_row.open,last_row.high,last_row.low,last_row.close,last_row.volume,last_row.ST,last_row.STX,'side=sell'if last_row.STX=='red' else 'side=buy','qty=2','change=True' if last_row.STX!=last_signal else 'change=False')
# #         adding data in file here
#         f = open("marketData.txt", "a")
#         d = f"{datetime.datetime.now()},{last_time,last_row.Timestamp},{last_row.open},{last_row.high},{last_row.low},{last_row.close},{last_row.volume},{last_row.ST},{last_row.STX},{'side=sell'if last_row.STX=='red' else 'side=buy'},{'qty=2'},{'change=True' if last_row.STX!=last_signal else 'change=False'}"
#         f.write(d)
#         print(f"{datetime.datetime.now()},{last_time,last_row.Timestamp},{last_row.open},{last_row.high},{last_row.low},{last_row.close},{last_row.volume},{last_row.ST},{last_row.STX},{'side=sell'if last_row.STX=='red' else 'side=buy'},{'qty=2'},{'change=True' if last_row.STX!=last_signal else 'change=False'}")

#         last_signal=last_row.STX
#         if last_row.STX!=last_signal:
#             print("order called")
#             order_plc =  place_order(ROOT_ENDPOINT,headers,"NSE","ICICIBANK",1000,'SELL'if last_row.STX=='red' else 'BUY')
#             print(order_plc)

running 2023-03-31 13:56:24.755773 2023-03-31T13:51:00+0530 2023-03-31T13:51:00+0530 3395.55 3397.95 3395.55 3397.5 972 3406.33 red side=sell qty=1 change=True

In [7]:
df

,Timestamp,open,high,low,close,volume,ATR,final_ub,final_lb,ST,STX
0,2023-03-01T13:57:00+0530,3451.40,3452.80,3450.00,3451.00,200,0.000000,0.00,0.00,0.00,NA
1,2023-03-01T14:00:00+0530,3451.00,3451.00,3445.00,3445.10,964,0.600000,3449.80,3446.20,3449.80,red
2,2023-03-01T14:03:00+0530,3446.20,3446.95,3440.65,3441.70,451,1.170000,3447.31,3440.29,3447.31,red
3,2023-03-01T14:06:00+0530,3443.70,3444.50,3440.15,3441.05,520,1.488000,3446.79,3440.29,3446.79,red
4,2023-03-01T14:09:00+0530,3443.05,3445.00,3440.75,3445.00,332,1.764200,3446.79,3440.29,3446.79,red
...,...,...,...,...,...,...,...,...,...,...,...
2494,2023-03-31T13:39:00+0530,3401.25,3401.40,3390.05,3391.20,5627,4.580729,3407.96,3394.90,3407.96,red
2495,2023-03-31T13:42:00+0530,3391.20,3394.95,3390.00,3393.45,627,4.617656,3406.33,3378.62,3406.33,red
2496,2023-03-31T13:45:00+0530,3392.95,3395.00,3392.75,3394.75,478,4.380890,3406.33,3380.73,3406.33,red
2497,2023-03-31T13:48:00+0530,3394.75,3397.15,3393.00,3395.20,395,4.357801,3406.33,3382.00,3406.33,red
2498,2023-03-31T13:51:00+0530,3395.55,3397.95,3395.55,3397.50,972,4.197021,3406.33,3384.16,3406.33,red

In [11]:
df

,Timestamp,open,high,low,close,volume,ATR,final_ub,final_lb,ST,STX
0,2023-03-01T14:03:00+0530,3446.90,3446.95,3440.65,3441.70,353,0.000000,0.00,0.00,0.00,NA
1,2023-03-01T14:06:00+0530,3443.70,3444.50,3440.15,3441.05,520,0.435000,3443.63,3441.02,3443.63,red
2,2023-03-01T14:09:00+0530,3443.05,3445.00,3440.75,3445.00,332,0.816500,3443.63,3441.02,3441.02,green
3,2023-03-01T14:12:00+0530,3445.00,3447.00,3442.95,3447.00,593,1.139850,3448.39,3441.56,3441.56,green
4,2023-03-01T14:15:00+0530,3447.00,3447.00,3445.40,3447.00,424,1.185865,3448.39,3442.64,3442.64,green
...,...,...,...,...,...,...,...,...,...,...,...
2495,2023-03-31T13:48:00+0530,3394.75,3397.15,3393.00,3395.20,395,4.357801,3406.33,3382.00,3406.33,red
2496,2023-03-31T13:51:00+0530,3395.55,3397.95,3395.55,3397.50,972,4.197021,3406.33,3384.16,3406.33,red
2497,2023-03-31T13:54:00+0530,3397.50,3401.25,3395.15,3399.35,2178,4.387319,3406.33,3385.04,3406.33,red
2498,2023-03-31T13:57:00+0530,3399.35,3401.20,3397.00,3400.00,699,4.368587,3406.33,3385.99,3406.33,red
2499,2023-03-31T14:00:00+0530,3400.00,3405.00,3398.35,3402.05,1704,4.596728,3406.33,3387.88,3406.33,red

running 2023-03-31 14:06:09.749169 2023-03-31T14:03:00+0530 2023-03-31T14:03:00+0530 3401.0 3401.0 3400.0 3400.05 155 3406.33 red side=sell qty=2 change=False
running 2023-03-31 14:09:07.936851 2023-03-31T14:06:00+0530 2023-03-31T14:06:00+0530 3398.55 3398.55 3396.7 3397.9 184 3406.33 red side=sell qty=2 change=False
running 2023-03-31 14:12:08.356932 2023-03-31T14:09:00+0530 2023-03-31T14:09:00+0530 3395.2 3396.3 3393.05 3395.9 197 3406.33 red side=sell qty=2 change=False
running 2023-03-31 14:15:08.546689 2023-03-31T14:12:00+0530 2023-03-31T14:12:00+0530 3395.65 3396.0 3395.45 3396.0 189 3406.33 red side=sell qty=2 change=False
running 2023-03-31 14:18:08.903661 2023-03-31T14:15:00+0530 2023-03-31T14:15:00+0530 3394.0 3397.0 3393.2 3393.3 179 3406.33 red side=sell qty=2 change=False
running 2023-03-31 14:21:08.453864 2023-03-31T14:18:00+0530 2023-03-31T14:18:00+0530 3392.4 3395.6 3392.4 3394.0 219 3406.33 red side=sell qty=2 change=False

Exception in thread Thread-5 (getDataThread):
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Python310\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000287A18F9C30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.kite.trade', port=443): Max retries exceeded with url: /instruments/historical/5097729/3minute?from=2023-03-01%2017:23:30.197078&to=2023-03-31%2017:20:30.197078 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287A18F9C30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Rplus\AppData\Local\Temp\ipykernel_5332\773829961.py", line 8, in getDataThread
  File "C:\Users\Rplus\AppData\Local\Temp\ipykernel_5332\1043667789.py", line 3, in getData
  File "C:\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python310\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.kite.trade', port=443): Max retries exceeded with url: /instruments/historical/5097729/3minute?from=2023-03-01%2017:23:30.197078&to=2023-03-31%2017:20:30.197078 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287A18F9C30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))